service:
  name: sls-first

plugins:
  - serverless-bundle
  - serverless-pseudo-parameters

provider:
  name: aws
  runtime: nodejs12.x
  memorySize: 256
  stage: ${opt:stage, 'dev'}
  region: ap-south-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:PutItem
      Resource:
        - arn:aws:dynamodb:#{AWS::Region}:#{AWS::AccountId}:table/MonthlyBudget

resources:
  Resources:
    BudgetTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: MonthlyBudget
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH


functions:
  createBudget:
    handler: src/handlers/createBudget.handler
    events:
      - http:
          method: POST
          path: /createBudget
