service:
  name: sls-first

plugins:
  - serverless-bundle
  - serverless-pseudo-parameters

provider:
  name: aws
  runtime: nodejs12.x
  memorySize: 256
  stage: ${opt:stage, 'dev'}
  region: ap-south-1
  iamRoleStatements:
    - ${file(iam/BudgetTableIAM.yaml):BudgetTableIAM}

resources:
  Resources:
    BudgetTable: ${file(resources/BudgetTable.yaml):BudgetTable}


functions:
  createBudget:
    handler: src/handlers/createBudget.handler
    events:
      - http:
          method: POST
          path: /createBudget
